-keep class com.herohan.uvcapp.** { *; }
-keep class com.serenegiant.usb.** { *; }
-keepclassmembers class * implements com.serenegiant.usb.IButtonCallback {*;}
-keep class * implements com.serenegiant.usb.IFrameCallback { *; }
-keepclassmembers class * implements com.serenegiant.usb.IStatusCallback {*;}
